# check all the available dates for the appointments
GET http://localhost:8000/api/v1/availability
Content-Type: application/application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThlNmY5YWU3MDkxYzA5ZDhmZTcwNyIsIm5hbWUiOiJVc2VyIG9uZSIsImVtYWlsIjoiYmF4b2phNzA5N0BldG9weXMuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTM4NjA2NTEsImV4cCI6MTcxMzg2NDI1MX0.ygwdGzDI-DmXgot16i25NPLqF_EVggBhc46qPTdPjio
###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "name": "Prosourav One",
  "email":"prosourav49@gmail.com",
  "password":"Test@123"
}

###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email":"dev.souravsaha@gmail.com",
  "password":"Test@123"
}

###
POST http://localhost:8000/api/v1/auth/refresh
Content-Type: application/json

{
  "id":"6524fe9dea75f922eba95436",
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjRmZjI1ZWE3NWY5MjJlYmE5NTQzZCIsInVzZXIiOiI2NTI0ZmU5ZGVhNzVmOTIyZWJhOTU0MzYiLCJuYW1lIjoiVGVzdHVzZXIiLCJlbWFpbCI6InBvbWFpa2FpMzUxQHJhcGlkbHl3cy5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY5NjkyMzQyOSwiZXhwIjoxNjk5NTE1NDI5fQ.naneEtvp76IjSFn5wBG9pel879CvNyc3gzU_zEwkVqQ"
}

###
GET http://localhost:8000/api/v1/auth/verify/
Content-Type: application/json

###
POST  http://localhost:8000/api/v1/auth/logout?id=6524fe9dea75f922eba95436
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjgyMTQyZTY1MjY3ZTg2M2RlY2QxMSIsIm5hbWUiOiJEZXZzb3VyYXYiLCJlbWFpbCI6ImRldi5zb3VyYXZzYWhhQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjk3NjUwNjY0LCJleHAiOjE2OTc2NTI0NjR9.29_8OXSb7pBS6a_GZGAP-gXYZB1XUii1MJkHpERG-Mw

###
GET  http://localhost:8000/api/v1/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThlMzExZDlkYTBiZTM2MWZmNWJmMSIsIm5hbWUiOiJBZG1pbiBhZG1pbiIsImVtYWlsIjoic291cmF2LnNhaGFAY29kZWNsb3Vkcy5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTM1MjI3OTUsImV4cCI6MTcxMzUyNjM5NX0.VqkYOfa3z0rZFzSOz-jJOzZeRRpZVmcYkVznR_IOLeA
###
POST  http://localhost:8000/api/v1/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkNDEwOTBkMzljNDlkZWY1Nzk2YiIsIm5hbWUiOiJQcm9zb3VyYXYiLCJlbWFpbCI6InByb3NvdXJhdjQ5QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjk4MzgyNDcyLCJleHAiOjE2OTgzODQyNzJ9.Cq6L7CXEm0vmtM-KDIYCR90nNrqZVzPASsM5KBtuvmo

{
  "vaccine": "Covid",
  "date": "2023-10-29"
}

###
PATCH   http://localhost:8000/api/v1/appointments/6537ef4976f339dd8e4cbbfe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkMzQ2OTBkMzljNDlkZWY1Nzk2NSIsIm5hbWUiOiJEZXZzb3VyYXYiLCJlbWFpbCI6ImRldi5zb3VyYXZzYWhhQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5ODE2NjgzMiwiZXhwIjoxNjk4MTY4NjMyfQ.N9iqGUzWZZ68P5kHJPjvkuPyQ6cMvMy4aLhcVSXWFYA

{
  "date": "2023-10-24"
}
###
GET  http://localhost:8000/api/v1/appointments?page=1&limit=3&sort_by=createdAt&sort_type=dsc&search=&status=complete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2QwMWE5YjBmNTMzOGRiZDM1YjA2ZCIsIm5hbWUiOiJVc2VyIE9uZSIsImVtYWlsIjoic291cmF2c2FoYTExM0B5YWhvby5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY5ODQ5ODQ4OCwiZXhwIjoxNjk4NTAwMjg4fQ.gn5jcoPWRdFYT66SkNJpiOKjozROrVvsy6bYYJjt3Pw


###
PATCH  http://localhost:8000/api/v1/appointments/complete/653d038f5284342d85d6a3f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2NmODhlZWQxY2Q3NDk5Y2RlNTc5NSIsIm5hbWUiOiJTb3VyYXYgU2FoYSIsImVtYWlsIjoiZGV2LnNvdXJhdnNhaGFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk4NTYyOTE5LCJleHAiOjE2OTg1NjQ3MTl9.F62y28rJPLISaaEnwp5piyQQ9HS_iqa0-92bj95GhuA

###
GET  http://localhost:8000/api/v1/appointments/6533d6dd90d39c49def57991?expand=user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkNDZkOTBkMzljNDlkZWY1Nzk3MSIsIm5hbWUiOiJTb3VyYXYiLCJlbWFpbCI6InNvdXJhdnNhaGExMTNAeWFob28uY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2OTc5ODEwMzQsImV4cCI6MTY5Nzk4MjgzNH0.iof0b6j1fQOhdZxItjhP2CnCW7qBwMGer97GnEdxV0o

###
DELETE http://localhost:8000/api/v1/appointments/6533d66d90d39c49def57985
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkMzQ2OTBkMzljNDlkZWY1Nzk2NSIsIm5hbWUiOiJEZXZzb3VyYXYiLCJlbWFpbCI6ImRldi5zb3VyYXZzYWhhQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5ODE2Mzg4NCwiZXhwIjoxNjk4MTY1Njg0fQ.1o2AsbmrMpmjKRbt7BqsswXI-tUO2bZ-AOR2M8GJm7I


###
GET  http://localhost:8000/api/v1/reviews?page=1&limit=2&sort_by=createdAt&sort_type=dsc&status=pending&filter=&expand=user,appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2NmODhlZWQxY2Q3NDk5Y2RlNTc5NSIsIm5hbWUiOiJTb3VyYXYgU2FoYSIsImVtYWlsIjoiZGV2LnNvdXJhdnNhaGFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk4NTc2NTAzLCJleHAiOjE2OTg1NzgzMDN9.z32KitQfFiuRpHdcc0h_pzWaffrUCCTzjZdl7dN3MRc

# to be continued
###
POST http://localhost:8000/api/v1/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2NmODhlZWQxY2Q3NDk5Y2RlNTc5NSIsIm5hbWUiOiJTb3VyYXYgU2FoYSIsImVtYWlsIjoiZGV2LnNvdXJhdnNhaGFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk4NTcxMzU4LCJleHAiOjE2OTg1NzMxNTh9.w0Y8dL3QnuphAoDnrXqE9X14QBctLVLPHk9n3UBKoLU

{
  "body": "1st comment of alamin viaya",
  "appointmentId": "653b42aa92743e903590d113"
}

###
PATCH http://localhost:8000/api/v1/reviews/65395f25dc447c01ce04fc85
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkNDZkOTBkMzljNDlkZWY1Nzk3MSIsIm5hbWUiOiJTb3VyYXYiLCJlbWFpbCI6InNvdXJhdnNhaGExMTNAeWFob28uY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2OTgyOTc5NDcsImV4cCI6MTY5ODI5OTc0N30.b45_9cDdRr0ugSn7zv3uAgQc-TcAZxl8GR2o4R8fmM4

{
  "body": "3nd comment",
  "status": "approved"
}

###
DELETE  http://localhost:8000/api/v1/reviews/65395f25dc447c01ce04fc85
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkNDZkOTBkMzljNDlkZWY1Nzk3MSIsIm5hbWUiOiJTb3VyYXYiLCJlbWFpbCI6InNvdXJhdnNhaGExMTNAeWFob28uY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2OTgyOTc5NDcsImV4cCI6MTY5ODI5OTc0N30.b45_9cDdRr0ugSn7zv3uAgQc-TcAZxl8GR2o4R8fmM4

###
GET http://localhost:8000/api/v1/users?page=1&limit=10&sort_by=name&sort_type=asc&search=sou&filter=approved
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkMzQ2OTBkMzljNDlkZWY1Nzk2NSIsIm5hbWUiOiJEZXZzb3VyYXYiLCJlbWFpbCI6ImRldi5zb3VyYXZzYWhhQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5ODM0MTg4NiwiZXhwIjoxNjk4MzQzNjg2fQ.7DioiUv7LxJnTSU8iJYNZKAxwEIv0IxUbHLmLveQfmM

###
POST  http://localhost:8000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkMzQ2OTBkMzljNDlkZWY1Nzk2NSIsIm5hbWUiOiJEZXZzb3VyYXYiLCJlbWFpbCI6ImRldi5zb3VyYXZzYWhhQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5ODM0MTg4NiwiZXhwIjoxNjk4MzQzNjg2fQ.7DioiUv7LxJnTSU8iJYNZKAxwEIv0IxUbHLmLveQfmM

{
  "name": "newUser4",
  "email":"sourav@codeclouds.com",
  "password":"PassWord123"
}

###
GET http://localhost:8000/api/v1/users/6618e311d9da0be361ff5bf1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThlMzExZDlkYTBiZTM2MWZmNWJmMSIsIm5hbWUiOiJBZG1pbiBhZG1pbiIsImVtYWlsIjoic291cmF2LnNhaGFAY29kZWNsb3Vkcy5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTM1MjI3OTUsImV4cCI6MTcxMzUyNjM5NX0.VqkYOfa3z0rZFzSOz-jJOzZeRRpZVmcYkVznR_IOLeA

###
PATCH  http://localhost:8000/api/v1/users/6618e311d9da0be361ff5bf1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzNkMzQ2OTBkMzljNDlkZWY1Nzk2NSIsIm5hbWUiOiJEZXZzb3VyYXYiLCJlbWFpbCI6ImRldi5zb3VyYXZzYWhhQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5ODM0Mzk0MywiZXhwIjoxNjk4MzQ1NzQzfQ.-zHdswF9y7wz98Ta_-YeqbXFRHgPThZMl4fvUfquW8k

{
  "name": "Alamin",
  "photo": "http://random.com"
}

###
DELETE http://localhost:8000/api/v1/users/64fffac6b90e61e60d4ccb02
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDAxNmFkYzllZDc1OTMzZTQ1NDkzMyIsIm5hbWUiOiJTb3VyYXYgU2FoYSIsImVtYWlsIjoic291cmF2QGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2OTQ4OTQ5MTUsImV4cCI6MTY5NDkzMDkxNX0.VGGhdNI8RdqyRBigBQ5mwIgKSVHtYBNasRUP_bO7vUE


###
PATCH http://localhost:8000/api/v1/change_admin/650016adc9ed75933e454933
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDAxOTEwYzllZDc1OTMzZTQ1NDk0MiIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTUzOTgxNzIsImV4cCI6MTY5NTQzNDE3Mn0.fUS0WO0QM6DR77rU6ZZlfC2Pho_5LTT1Zk0284ilUXo


###
POST http://localhost:8000/api/v1/vaccines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2NmODhlZWQxY2Q3NDk5Y2RlNTc5NSIsIm5hbWUiOiJTb3VyYXYgU2FoYSIsImVtYWlsIjoiZGV2LnNvdXJhdnNhaGFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk4NTYyOTE5LCJleHAiOjE2OTg1NjQ3MTl9.F62y28rJPLISaaEnwp5piyQQ9HS_iqa0-92bj95GhuA

{
  "name":"Pneumonia"
}

//chat
###
POST http://localhost:8000/api/v1/conversations/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThlNmY5YWU3MDkxYzA5ZDhmZTcwNyIsIm5hbWUiOiJVc2VyIG9uZSIsImVtYWlsIjoiYmF4b2phNzA5N0BldG9weXMuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTM5NTk3MzAsImV4cCI6MTcxMzk2MzMzMH0.8IW9H8nxhabCCL046VIrGDRcCoBmLDEq0ycnAZPNDIs

{
  "senderId":"6618e6f9ae7091c09d8fe707",
  "receiverId":"661cd57beb955d517a4a87ba"
}

###

POST http://localhost:8000/api/v1/conversations/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThlNmY5YWU3MDkxYzA5ZDhmZTcwNyIsIm5hbWUiOiJVc2VyIG9uZSIsImVtYWlsIjoiYmF4b2phNzA5N0BldG9weXMuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTM5NTQ5MTAsImV4cCI6MTcxMzk1ODUxMH0.ZRCbAryWfEQS2BIxhtCZpbYf5Gh6PFDXOmirYgxwSRQ

{
  "senderId":"6618e6f9ae7091c09d8fe707",
  "receiverId":"66226899b4dc0a86e844e124"
}

###
POST http://localhost:8000/api/v1/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThlNmY5YWU3MDkxYzA5ZDhmZTcwNyIsIm5hbWUiOiJVc2VyIG9uZSIsImVtYWlsIjoiYmF4b2phNzA5N0BldG9weXMuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTM5NTQ5MTAsImV4cCI6MTcxMzk1ODUxMH0.ZRCbAryWfEQS2BIxhtCZpbYf5Gh6PFDXOmirYgxwSRQ

{
    "conversationId":"6628e114d5d11cdfc30a1d11",
    "senderId": "66226899b4dc0a86e844e124",
    "receiverId": "6618e6f9ae7091c09d8fe707",
    "text": "test msg"
}

###

GET  http://localhost:8000/api/v1/messages/6628e114d5d11cdfc30a1d11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThlNmY5YWU3MDkxYzA5ZDhmZTcwNyIsIm5hbWUiOiJVc2VyIG9uZSIsImVtYWlsIjoiYmF4b2phNzA5N0BldG9weXMuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTM5NTQ5MTAsImV4cCI6MTcxMzk1ODUxMH0.ZRCbAryWfEQS2BIxhtCZpbYf5Gh6PFDXOmirYgxwSRQ

###